#!/bin/bash 
# 
# This script runs a Turbomole job using SMP parallelization 
# 
# Grid Engine options 
#$ -N chQE2HC # Name this job 
#$ -cwd # use current working directory 
#$ -o test.out # specify an output file - change 'outputfile.out' 
#$ -j y # and put all output (inc errors) into it 
#$ -pe smp 8 # Request N CPU cores 
#$ -l h_vmem=4G # Request 1GB RAM / core, i.e. 4GB total
#$ -l h_rt=240:0:0 # Request 240 hour runtime (max allowed) 
#$ -l s_rt=239:55:0 # Time at which data will copy from scratch to working directory
#$ -m ea # Send email at end of job and if aborted

module load qe-mpi
pw.x < qe.in> qe.out




