#!/bin/bash 
# 
# This script runs a Gaussian job 
# 
# Grid Engine options 
#$ -N Jmon_1  # Name this job 
#
#$ -cwd # use current working directory 
#$ -o test.out # specify an output file - change 'outputfile.out' 
#$ -j y # and put all output (inc errors) into it 
#$ -pe smp 4 # Request 4 CPU cores 
#$ -l h_rt=240:0:0 # Request 24 hour runtime (upto 240 hours) 
#$ -l h_vmem=2G # Request 1GB RAM / core, i.e. 4GB total 
#$ -m ea # Send email at end of job and if aborted
# Load the gaussian software and environment variables for you 

module load gaussian

# The following command runs Gaussian using <input file> and prints to "output_file" 

# g09 <input-file> output_file


g09 $1.com $1.out



